---
# Line length
# https://github.com/DavidAnson/markdownlint/blob/v0.19.0/doc/Rules.md#md013
MD013: false

# Multiple headings with the same content
# https://github.com/DavidAnson/markdownlint/blob/v0.19.0/doc/Rules.md#md024
MD024:
  allow_different_nesting: true

# Multiple top level headings in the same document
# https://github.com/DavidAnson/markdownlint/blob/v0.19.0/doc/Rules.md#md025
MD025:
  front_matter_title: ""

# Spaces after list markers
# https://github.com/DavidAnson/markdownlint/blob/v0.19.0/doc/Rules.md#md030---spaces-after-list-markers
MD030:
  # Match editorconfig tab size set to 4 spaces
  ul_single: 3
  ol_single: 1
  ul_multi: 3
  ol_multi: 1

# Inline HTML
# https://github.com/DavidAnson/markdownlint/blob/v0.19.0/doc/Rules.md#md033---inline-html
MD033:
  allowed_elements:
    # Allow inline html tags of terraform-docs
    - a
    - br
    - pre
