# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Powershell project to Azure Function App - cwa-func-ar-secrets-prod-func (Preview)

on:
  push:
    branches-ignore:
      - main
    paths:
      - "functions/**"
      - ".github/workflows/**"
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./functions" # set this to the path to your web app project, defaults to the repository root

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: "cwa-func-ar-secrets-prod-func"
          slot-name: "preview"
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          respect-funcignore: true
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
